### PR TITLE
correctly handle spaces in filenames

### PR DESCRIPTION
**Pull request by drewelmore**

### CODE REVIEW

**Comment by lf94** [comment]
Please quote $EDITOR too.

**Comment by Julian** [comment]
This doesn't look correct to me -- it looks like you're trying to support `peek foo bar.txt`, but that should have been written `peek 'foo bar.txt'`, i.e., the user should have quoted it.

As is, you'll break passing additional options along, which is what this did originally.

**Comment by lf94** [comment]
@Julian yes good point. What do you suggest?

**Comment by drewelmore** [comment]
> This doesn't look correct to me -- it looks like you're trying to support `peek foo bar.txt`, but that should have been written `peek 'foo bar.txt'`, i.e., the user should have quoted it.
> 
> As is, you'll break passing additional options along, which is what this did originally.

The use case supports one or more filenames with spaces.  If the user has properly quoted the arguments to the command, for example:

`peek "My File With Spaces" foo.txt`

"$@" is shell's construct to properly handle those separate arguments; it's not simply wrapping $@ in quotes.  From the bash man page:  

> When  the  expansion  occurs  within double quotes, each parameter expands to a separate word. 
> That is, "$@" is equivalent to "$1" "$2" ...

So in the example above, 
* "$@" expands to "My File With Spaces" "foo.txt"
* $@ exands to My File With Spaces foo.txt

**Comment by lf94** [comment]
Ah cool! Thanks for the lesson.

Merged :)

**Comment by Julian** [comment]
@drewelmore ah interesting, thanks, good to know here too.

**Pull request merged**
